[[redirects]]
  from = "/newyearbogo"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true


# [[redirects]]
#   from = "/spookybogo"
#   to = "https://join.ketokrate.com/getbundle"
#   status = 302
#   force = true

# [[redirects]]
#   from = "/bogo"
#   to = "https://join.ketokrate.com/getbundle"
#   status = 302
#   force = true

# [[redirects]]
#   from = "/subscribe-bogo"
#   to = "https://join.ketokrate.com/getbundle"
#   status = 302
#   force = true

[[redirects]]
  from = "/30-off"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true

# [[redirects]]
#   from = "/black-friday-came-early"
#   to = "https://join.ketokrate.com/getbundle"
#   status = 302
#   force = true

# [[redirects]]
#   from = "/black-friday-deal"
#   to = "https://join.ketokrate.com/getbundle"
#   status = 302
#   force = true

[[redirects]]
  from = "/cyber-monday-sale"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true

[[redirects]]
  from = "/christmas-special"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true

[[redirects]]
  from = "/2krazyketos/"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true

  # [[redirects]]
  # from = "/bf-bogo"
  # to = "https://join.ketokrate.com/getbundle"
  # status = 302
  # force = true

  [[redirects]]
  from = "cm-bogo"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true

  [[redirects]]
  from = "msa-bogo"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true

  [[redirects]]
  from = "newyear"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true

  [[redirects]]
  from = "newyear-bogo"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true

  [[redirects]]
  from = "stay-25"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true

  [[redirects]]
  from = "25-off"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true

  [[redirects]]
  from = "curlygirlz"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true

  [[redirects]]
  from = "ketoguide"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true

  [[redirects]]
  from = "memorialday"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true

  [[redirects]]
  from = "bundle"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true

  [[redirects]]
  from = "snackfun"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true

  [[redirects]]
  from = "25plus"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true

  # [[redirects]]
  # from = "blackfriday"
  # to = "https://join.ketokrate.com/getbundle"
  # status = 302
  # force = true

  [[redirects]]
  from = "fabfitfun"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true

  [[redirects]]
  from = "/"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true

  [[redirects]]
  from = "ketogenicplus"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true

  [[redirects]]
  from = "kkguide"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true

  [[redirects]]
  from = "prepaid"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true

  [[redirects]]
  from = "spookybogorecharge"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true

  [[redirects]]
  from = "summer"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true

  [[redirects]]
  from = "cybermonday"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true

  [[redirects]]
  from = "lowcarbyum"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true

  [[redirects]]
  from = "ketogenicplus"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true

  # [[redirects]]
  # from = "bogoplus"
  # to = "https://join.ketokrate.com/getbundle"
  # status = 302
  # force = true

  [[redirects]]
  from = "holiday"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true

  [[redirects]]
  from = "merry-bogo"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true

  [[redirects]]
  from = "beyond"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true

  [[redirects]]
  from = "newyear2024"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true

  [[redirects]]
  from = "newyear20242"
  to = "https://join.ketokrate.com/getbundle"
  status = 302
  force = true

# endpoints live (merry-bogo, bogoplus, merry-bogo) 