[[redirects]]
  from = "/newyearbogo"
  to = "https://join.ketokrate.com/25-off"
  status = 302
  force = true


[[redirects]]
  from = "/spookybogo"
  to = "https://join.ketokrate.com/25-off"
  status = 302
  force = true

[[redirects]]
  from = "/bogo"
  to = "https://join.ketokrate.com/25-off"
  status = 302
  force = true

[[redirects]]
  from = "/subscribe-bogo"
  to = "https://join.ketokrate.com/25-off"
  status = 302
  force = true


[[redirects]]
  from = "/30-off"
  to = "https://join.ketokrate.com/25-off"
  status = 302
  force = true

[[redirects]]
  from = "/black-friday-came-early"
  to = "https://join.ketokrate.com"
  status = 302
  force = true

[[redirects]]
  from = "/black-friday-deal"
  to = "https://join.ketokrate.com"
  status = 302
  force = true

[[redirects]]
  from = "/cyber-monday-sale"
  to = "https://join.ketokrate.com"
  status = 302
  force = true

[[redirects]]
  from = "/christmas-special"
  to = "https://join.ketokrate.com"
  status = 302
  force = true

[[redirects]]
  from = "/2krazyketos/"
  to = "https://join.ketokrate.com/25plus"
  status = 302
  force = true

  [[redirects]]
  from = "/bf-bogo"
  to = "https://join.ketokrate.com/merry-bogo"
  status = 302
  force = true

  [[redirects]]
  from = "cm-bogo"
  to = "https://join.ketokrate.com/merry-bogo"
  status = 302
  force = true

  [[redirects]]
  from = "merry-bogo"
  to = "https://join.ketokrate.com/newyear-bogo"
  status = 302
  force = true

  [[redirects]]
  from = "msa-bogo"
  to = "https://join.ketokrate.com/bogoplus"
  status = 302
  force = true

  [[redirects]]
  from = "newyear"
  to = "https://join.ketokrate.com/bogoplus"
  status = 302
  force = true

  [[redirects]]
  from = "newyear-bogo"
  to = "https://join.ketokrate.com/bogoplus"
  status = 302
  force = true

  [[redirects]]
  from = "stay-25"
  to = "https://join.ketokrate.com/25plus"
  status = 302
  force = true

  [[redirects]]
  from = "25-off"
  to = "https://join.ketokrate.com/25plus"
  status = 302
  force = true

  [[redirects]]
  from = "curlygirlz"
  to = "https://join.ketokrate.com"
  status = 302
  force = true

  [[redirects]]
  from = "ketoguide"
  to = "https://join.ketokrate.com/25plus"
  status = 302
  force = true

  [[redirects]]
  from = "memorialday"
  to = "https://join.ketokrate.com/summer"
  status = 302
  force = true

  [[redirects]]
  from = "blackfriday"
  to = "https://join.ketokrate.com/bundle"
  status = 302
  force = true

  [[redirects]]
  from = "bf-bogo"
  to = "https://join.ketokrate.com/bundle"
  status = 302
  force = true

  [[redirects]]
  from = "cm-bogo"
  to = "https://join.ketokrate.com/bundle"
  status = 302
  force = true

  [[redirects]]
  from = "cybermonday"
  to = "https://join.ketokrate.com/bundle"
  status = 302
  force = true

  [[redirects]]
  from = "bogoplus"
  to = "https://join.ketokrate.com/25-off"
  status = 302
  force = true

  [[redirects]]
  from = "25plus"
  to = "https://www.ketokrate.com/pages/prepay-and-save"
  status = 302
  force = true

  [[redirects]]
  from = "bundle"
  to = "https://www.ketokrate.com/pages/prepay-and-save"
  status = 302
  force = true

  [[redirects]]
  from = "snackfun"
  to = "https://www.ketokrate.com/pages/prepay-and-save"
  status = 302
  force = true