[[redirects]]
  from = "/newyearbogo"
  to = "https://join.ketokrate.com/"
  status = 302
  force = true


[[redirects]]
  from = "/spookybogo"
  to = "https://join.ketokrate.com/"
  status = 302
  force = true

[[redirects]]
  from = "/bogo"
  to = "https://join.ketokrate.com/"
  status = 302
  force = true

[[redirects]]
  from = "/subscribe-bogo"
  to = "https://join.ketokrate.com/"
  status = 302
  force = true